(executable
 (flags :standard -w -3)
 (libraries threads google_drive_ocamlfuse ounit2 yojson)
 (name e2eSuite))

(rule
 (alias e2e)
 (deps e2eSuite.exe ../../bin/gdfuse.exe)
 (action (run ./e2eSuite.exe)))

(rule
 (alias e2e-list)
 (deps e2eSuite.exe)
 (action (run ./e2eSuite.exe --list)))

(rule
 (alias e2e-preflight)
 (deps e2eSuite.exe ../../bin/gdfuse.exe)
 (action (run ./e2eSuite.exe --preflight)))
